// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4610.Test.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4610.Test.Robot;
import org.usfirst.frc4610.Test.RobotMap;

/**
 *
 */
public class AutonomousCommand extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousCommand() {
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    double beginmatch;
    // Called just before this Command runs the first time
    protected void initialize() {
    	beginmatch=Timer.getFPGATimestamp();

    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	

   		RobotMap.driveTrainleftBack.set(0.265);
   		RobotMap.driveTrainrightBack.set(-0.265);
   		RobotMap.driveTrainleftFront.set(0.265);
   		RobotMap.driveTrainrightFront.set(-0.265);
   		Timer.delay(3);
   	//	RobotMap.driveTrainleftBack.set(-0.8);
   	//	RobotMap.driveTrainrightBack.set(-0.8);
   //		Timer.delay(1.3);
   	//	RobotMap.driveTrainleftBack.set(0.8);
   // 	RobotMap.driveTrainrightBack.set(-0.8);
   //		Timer.delay(3);
   //		RobotMap.driveTrainleftBack.set(0.8);
   //		RobotMap.driveTrainrightBack.set(0.8);
   	//	Timer.delay(1.3);
   	//	RobotMap.driveTrainleftBack.set(-0.8);
   //		RobotMap.driveTrainrightBack.set(0.8);
   	//	Timer.delay(3);
   	//	RobotMap.driveTrainleftBack.set(0.8);
   	//	RobotMap.driveTrainrightBack.set(0.8);
   	//	Timer.delay(.8);
   	//	RobotMap.driveTrainleftBack.set(-0.8);
   	//	RobotMap.driveTrainrightBack.set(0.8);
   	//	Timer.delay(1.2);
   		//RobotMap.liftmotor.set(1.0);
   		//Timer.delay(2);
   		
   		
    		
    //	RobotMap.driveTrainleftFront.set(0.8);
    // 	RobotMap.driveTrainrightFront.set(0.8);   		}
    }


	// Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	if((Timer.getFPGATimestamp()-beginmatch)>1)
    		return true;

        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	RobotMap.driveTrainleftBack.set(0.0);
    	RobotMap.driveTrainleftFront.set(0.0);
    	RobotMap.driveTrainrightBack.set(0.0);
    	RobotMap.driveTrainrightFront.set(0.0);
  
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {

    }
}
